name: Validate themes
on:
  push:
    branches-ignore:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
    - name: Validating themes
      run: |
        echo using $(python3 --version)
        python3 .github/validation.py
